History.create(diagnoses: 'porcelin', medications: 'atarax', allergies: 'Betadine', current_treatments: 'soaks', surgeries: 'tonsillectomy', immunizations_with_dates: 'polio -1/14/67', patient_id: 7)
History.create(diagnoses: 'gout', medications: 'allopurinal', allergies: 'none', current_treatments: 'rubbing', surgeries: 'cholecystectomy', immunizations_with_dates: 'antra- 5/14/32', patient_id: 8)
History.create(diagnoses: 'porcelin', medications: 'atarax', allergies: 'lidocaine', current_treatments: 'soaks', surgeries: 'tonsillectomy', immunizations_with_dates: 'polio -1/14/67', patient_id: 9)
History.create(diagnoses: 'Hypertension', medications: 'lisinopril', allergies: 'codeine', current_treatments: 'massages', surgeries: 'partial nephrectomy', immunizations_with_dates: 'antra- 5/14/32', patient_id: 10)
Subjective.create(location: 'foot', observed_changes: 'dry', sensation_changes: 'itching', scale_1_to_10: '4', length_of_time: '2 months', patient_id: 7)
Subjective.create(location: 'hand', observed_changes: 'moist', sensation_changes: 'pinching', scale_1_to_10: '3', length_of_time: '1 year', patient_id: 8)
Subjective.create(location: 'abdomen', observed_changes: 'scaling', sensation_changes: 'burning', scale_1_to_10: '8', length_of_time: '8 months', patient_id: 9)
Subjective.create(location: 'neck', observed_changes: 'parched', sensation_changes: 'dull ache', scale_1_to_10: '2', length_of_time: '10 days', patient_id: 10)
Comment.create(identifier: '7-1', note: '7- first note', items_to_discuss: '7- first item', questions:'7- first question', patient_id: 7)
Comment.create(identifier: '7-2', note: '7- second note', items_to_discuss: '7- second item', questions:'7- second question', patient_id: 7)
Comment.create(identifier: '7-3', note: '7- third note', items_to_discuss: '7- third item', questions:'7- third question', patient_id: 7)
Comment.create(identifier: '8-1', note: '8- first note', items_to_discuss: '8- first item', questions:'8- first question', patient_id: 8)
Comment.create(identifier: '8-2', note: '8- second note', items_to_discuss: '8- second item', questions:'8- second question', patient_id: 8)
Comment.create(identifier: '8-3', note: '8- third note', items_to_discuss: '8- third item',    questions: '8- third question', patient_id: 8)
Comment.create(identifier: '9-1', note: '9- first note', items_to_discuss: '9- first item', questions:'9- first question', patient_id: 9)
Comment.create(identifier: '9-2', note: '9- second note', items_to_discuss: '9- second item', questions:'9- second question', patient_id: 9)
Comment.create(identifier: '9-3', note: '9- third note', items_to_discuss: '9- third item', questions:'9- third question', patient_id: 9)
Comment.create(identifier: '10-1', note: '10- first note', items_to_discuss: '10- first item', questions:'10- first question', patient_id: 10)
Comment.create(identifier: '10-2', note: '10- second note', items_to_discuss: '10- second item', questions:'10- second question', patient_id: 10)
Comment.create(identifier: '10-3', note: '10- third note', items_to_discuss: '10- third item', questions:'10- third qustion', patient_id: 10)
